# Minha primeira tabela :)

In [3]:
import pandas as pd

dados = {
    'Cor': ['Amarela', 'Verde', 'Amarela', 'Verde'],
    'Textura': ['Macia', 'Dura', 'Macia', 'Macia'],
    'Doce': ['Sim', 'Não', 'Sim', 'Sim']
}

tabela_mangas = pd.DataFrame(dados)
display(tabela_mangas)

       Cor Textura Doce
0  Amarela   Macia  Sim
1    Verde    Dura  Não
2  Amarela   Macia  Sim
3    Verde   Macia  Sim

# //Consultas

In [4]:
mangas_doces = tabela_mangas[tabela_mangas['Doce'] == 'Sim']
display(mangas_doces)

       Cor Textura Doce
0  Amarela   Macia  Sim
2  Amarela   Macia  Sim
3    Verde   Macia  Sim

In [6]:
def avaliar_manga(linha):
    saida = ''
    if linha['Doce'] == 'Sim' and linha['Textura'] == 'Macia':
        saida = 'Com certeza!'
    else:
        saida = 'Deixar no mercado'

    return saida

tabela_mangas['Comprar?'] = tabela_mangas.apply(avaliar_manga, axis=1)
display(tabela_mangas)

       Cor Textura Doce           Comprar?
0  Amarela   Macia  Sim       Com certeza!
1    Verde    Dura  Não  Deixar no mercado
2  Amarela   Macia  Sim       Com certeza!
3    Verde   Macia  Sim       Com certeza!

# **Estudo de Caso: *Titanic***

In [10]:
titanic_dados = pd.read_csv('/kaggle/input/competitions/titanic/train.csv')
display(titanic_dados.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
mulheres_sobreviventes = titanic_dados[(titanic_dados['Sex'] == "female") & (titanic_dados['Survived'] == 1)]
display(mulheres_sobreviventes.head())

homens_sobreviventes = titanic_dados[(titanic_dados['Sex'] == 'male') & (titanic_dados['Survived'] == 1)]
display(homens_sobreviventes.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S

In [17]:
titanic_dados = titanic_dados.drop('Cabin', axis=1)
display(titanic_dados.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S